//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports.Alice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sports_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sports_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sports.Alice.Resources.Sports.Resources", typeof(Sports_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У меня нет лучших комментариев.
        /// </summary>
        public static string BestComments_NoComments {
            get {
                return ResourceManager.GetString("BestComments.NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучшие комментарии под новостью.
        /// </summary>
        public static string BestComments_Title_Tts {
            get {
                return ResourceManager.GetString("BestComments.Title.Tts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лучшие комментарии.
        /// </summary>
        public static string Command_BestComments {
            get {
                return ResourceManager.GetString("Command.BestComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дальше.
        /// </summary>
        public static string Command_BestComments_Next {
            get {
                return ResourceManager.GetString("Command.BestComments.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to к новости.
        /// </summary>
        public static string Command_BestComments_OpenNewsArticle {
            get {
                return ResourceManager.GetString("Command.BestComments.OpenNewsArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to последние новости.
        /// </summary>
        public static string Command_LatestNews {
            get {
                return ResourceManager.GetString("Command.LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to главные новости.
        /// </summary>
        public static string Command_MainNews {
            get {
                return ResourceManager.GetString("Command.MainNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете попросить меня прочитать последние или главные новости спорта, а также лучшие комментарии под главными новостями.
        /// </summary>
        public static string Help_Text_Tts {
            get {
                return ResourceManager.GetString("Help.Text.Tts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последние новости.
        /// </summary>
        public static string LatestNews_Header {
            get {
                return ResourceManager.GetString("LatestNews.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вот последние новости.
        /// </summary>
        public static string LatestNews_Header_Tts {
            get {
                return ResourceManager.GetString("LatestNews.Header.Tts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У меня нет последний новостей.
        /// </summary>
        public static string LatestNews_NoNews {
            get {
                return ResourceManager.GetString("LatestNews.NoNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главные новости.
        /// </summary>
        public static string MainNews_Header {
            get {
                return ResourceManager.GetString("MainNews.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вот главные новости.
        /// </summary>
        public static string MainNews_Header_Tts {
            get {
                return ResourceManager.GetString("MainNews.Header.Tts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У меня нет главных новостей.
        /// </summary>
        public static string MainNews_NoNews {
            get {
                return ResourceManager.GetString("MainNews.NoNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to для перехода к следующий новости скажите: дальше.
        /// </summary>
        public static string Tips_BestComments_Next {
            get {
                return ResourceManager.GetString("Tips.BestComments.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы узнать дополнительные возможности скажите: помощь.
        /// </summary>
        public static string Tips_Help {
            get {
                return ResourceManager.GetString("Tips.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Вы можете попросить меня прочитать последние или главные новости спорта, а также лучшие комментарии под главными новостями с сайта sports.ru.
        /// </summary>
        public static string Welcome_Text {
            get {
                return ResourceManager.GetString("Welcome.Text", resourceCulture);
            }
        }
    }
}
